version: "3.3"

services:

  node6:
    build:
      context: ./test
      dockerfile: Dockerfile-node6
    user: "node"
    entrypoint: "/opt/inspector-carbon/test/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-carbon/
    working_dir: "/opt/inspector-carbon"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-carbon/.tmp/.npm/"
      - NODE_VERSION=6

  node7:
    build:
      context: ./test
      dockerfile: Dockerfile-node7
    user: "node"
    entrypoint: "/opt/inspector-carbon/test/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-carbon/
    working_dir: "/opt/inspector-carbon"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-carbon/.tmp/.npm/"
      - NODE_VERSION=7

  node8:
    build:
      context: ./test
      dockerfile: Dockerfile-node8
    user: "node"
    entrypoint: "/opt/inspector-carbon/test/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-carbon/
    working_dir: "/opt/inspector-carbon"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-carbon/.tmp/.npm/"
      - NODE_VERSION=8

  node9:
    build:
      context: ./test
      dockerfile: Dockerfile-node9
    user: "node"
    entrypoint: "/opt/inspector-carbon/test/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-carbon/
    working_dir: "/opt/inspector-carbon"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-carbon/.tmp/.npm/"
      - NODE_VERSION=9

  node10:
    build:
      context: ./test
      dockerfile: Dockerfile-node10
    user: "node"
    entrypoint: "/opt/inspector-carbon/test/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-carbon/
    working_dir: "/opt/inspector-carbon"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-carbon/.tmp/.npm/"
      - NODE_VERSION=10

  node11:
    build:
      context: ./test
      dockerfile: Dockerfile-node11
    user: "node"
    entrypoint: "/opt/inspector-carbon/test/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-carbon/
    working_dir: "/opt/inspector-carbon"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-carbon/.tmp/.npm/"
      - NODE_VERSION=11

  grafana:
    build:
      context: ./test-env/grafana
      args:
        TZ: Europe/Berlin
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      default:
        aliases:
         - grafana
    hostname: grafana

  graphite:
    build:
      context: ./test-env/graphite
      args:
        TZ: Europe/Berlin
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    restart: unless-stopped
    networks:
      default:
        aliases:
         - graphite
    hostname: graphite

  # test:
  #   build:
  #     context: ./test-env/nodejs
  #     args:
  #       TZ: Europe/Berlin
  #   command: ["node", "/dev/test/build/playground/playground.js"]
  #   working_dir: "/dev/test"
  #   restart: "no"
  #   volumes:
  #     - "./:/dev/test"
  #   networks:
  #     default:
