apiVersion: 1

# see http://docs.grafana.org/administration/provisioning/
datasources:
- name: Graphite
  type: graphite
  access: proxy
  url: http://graphite/
  isDefault: true
  editable: true
  jsonData:
    graphiteVersion: "1.1"
